# Generated by Django 5.1.4 on 2025-01-14 15:28

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0002_fundhouse_rename_phone_user_email_portfolio'),
    ]

    operations = [
        migrations.AlterField(
            model_name='user',
            name='email',
            field=models.CharField(db_index=True, max_length=30, unique=True),
        ),
    ]
